
package org.centralbank.client.unsecured;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UnsecuredService", targetNamespace = "http://centralbank.org/", wsdlLocation = "http://aos.czacm.org/bank/unsecured?wsdl")
public class UnsecuredService
    extends Service
{

    private final static URL UNSECUREDSERVICE_WSDL_LOCATION;
    private final static WebServiceException UNSECUREDSERVICE_EXCEPTION;
    private final static QName UNSECUREDSERVICE_QNAME = new QName("http://centralbank.org/", "UnsecuredService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://aos.czacm.org/bank/unsecured?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNSECUREDSERVICE_WSDL_LOCATION = url;
        UNSECUREDSERVICE_EXCEPTION = e;
    }

    public UnsecuredService() {
        super(__getWsdlLocation(), UNSECUREDSERVICE_QNAME);
    }

    public UnsecuredService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNSECUREDSERVICE_QNAME, features);
    }

    public UnsecuredService(URL wsdlLocation) {
        super(wsdlLocation, UNSECUREDSERVICE_QNAME);
    }

    public UnsecuredService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNSECUREDSERVICE_QNAME, features);
    }

    public UnsecuredService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UnsecuredService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankService
     */
    @WebEndpoint(name = "UnsecuredPort")
    public BankService getUnsecuredPort() {
        return super.getPort(new QName("http://centralbank.org/", "UnsecuredPort"), BankService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankService
     */
    @WebEndpoint(name = "UnsecuredPort")
    public BankService getUnsecuredPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://centralbank.org/", "UnsecuredPort"), BankService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNSECUREDSERVICE_EXCEPTION!= null) {
            throw UNSECUREDSERVICE_EXCEPTION;
        }
        return UNSECUREDSERVICE_WSDL_LOCATION;
    }

}
