
package org.centralbank.client.secured;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SecuredService", targetNamespace = "http://centralbank.org/", wsdlLocation = "http://aos.czacm.org/bank/secured?wsdl")
public class SecuredService
    extends Service
{

    private final static URL SECUREDSERVICE_WSDL_LOCATION;
    private final static WebServiceException SECUREDSERVICE_EXCEPTION;
    private final static QName SECUREDSERVICE_QNAME = new QName("http://centralbank.org/", "SecuredService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://aos.czacm.org/bank/secured?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECUREDSERVICE_WSDL_LOCATION = url;
        SECUREDSERVICE_EXCEPTION = e;
    }

    public SecuredService() {
        super(__getWsdlLocation(), SECUREDSERVICE_QNAME);
    }

    public SecuredService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECUREDSERVICE_QNAME, features);
    }

    public SecuredService(URL wsdlLocation) {
        super(wsdlLocation, SECUREDSERVICE_QNAME);
    }

    public SecuredService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECUREDSERVICE_QNAME, features);
    }

    public SecuredService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecuredService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankService
     */
    @WebEndpoint(name = "SecuredPort")
    public BankService getSecuredPort() {
        return super.getPort(new QName("http://centralbank.org/", "SecuredPort"), BankService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankService
     */
    @WebEndpoint(name = "SecuredPort")
    public BankService getSecuredPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://centralbank.org/", "SecuredPort"), BankService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECUREDSERVICE_EXCEPTION!= null) {
            throw SECUREDSERVICE_EXCEPTION;
        }
        return SECUREDSERVICE_WSDL_LOCATION;
    }

}
