
package org.centralbank.client.signed;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://centralbank.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param sourceAccount
     * @param money
     * @param targetAccount
     * @param note
     * @throws TransactionException
     */
    @WebMethod
    @RequestWrapper(localName = "newTransaction", targetNamespace = "http://centralbank.org/", className = "org.centralbank.client.signed.NewTransaction")
    @ResponseWrapper(localName = "newTransactionResponse", targetNamespace = "http://centralbank.org/", className = "org.centralbank.client.signed.NewTransactionResponse")
    public void newTransaction(
        @WebParam(name = "sourceAccount", targetNamespace = "")
        long sourceAccount,
        @WebParam(name = "targetAccount", targetNamespace = "")
        long targetAccount,
        @WebParam(name = "money", targetNamespace = "")
        long money,
        @WebParam(name = "note", targetNamespace = "")
        String note)
        throws TransactionException
    ;

}
